export { CarEditPage } from './ui/edit/CarEditPage'
export { CarIdLayout } from './ui/id/CarIdLayout'
export { CarIdLoading } from './ui/id/CarIdLoading'
export { CarIdPage } from './ui/id/CarIdPage'
export { CarNewPage } from './ui/new/CarNewPage'
